version: '3'
services:

  #PHP Service
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: marcospacheco/php-8.2
    container_name: app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/
    # command: bash -c "cd gerenciamento_veiculos && npm run dev"
    volumes:
      - ./:/var/www
      # - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "5173:5173"
    networks:
      - default
      - database
      
  #Nginx Service Gerenciamento Loja
  gerenciamento_veiculos:
    image: nginx:alpine
    container_name: gerenciamento_veiculos
    restart: always
    tty: true
    ports:
      - "86:80"
      - "445:443"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - default
      - database
      
#Docker Networks
networks:
  default:
    driver: bridge
  database:
    name: database_database
    external: true
